[package]
name = "shrewscriptions-rs"
version = "0.1.0"
edition = "2021"
description = "ORDINALS metaprotocol indexer"
license = "MIT"
repository = "https://github.com/kungfuflex/shrewscriptions-rs"
resolver = "2"

[dependencies]
alkanes-support = { git = "https://github.com/kungfuflex/alkanes-rs.git" }
protorune-support = { git = "https://github.com/kungfuflex/alkanes-rs.git" }
metashrew = { git = "https://github.com/kungfuflex/alkanes-rs.git" }
metashrew-support = { git = "https://github.com/kungfuflex/alkanes-rs.git" }
once_cell = "1.20.2"
bitcoin = "0.32.5"
serde_cbor = "0.11.2"
anyhow = "1.0.95"
bincode = "1.3.3"
serde = { version = "1.0.217", features = ["derive"] }
ordinals = "0.0.14"

[features]
dogecoin = []
bellscoin = []
luckycoin = []
fractal = []
mainnet = []
testnet = []

[lib]
crate-type = ["cdylib", "rlib"]
